---
# tasks for Elasticsearch Configure

- name: Copy Elasticsearch configure file.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
    backup: yes
  notify: restart elasticsearch

- name: Ensure Elasticsearch data base dir is exists.
  file:
    path: '{{ elasticsearch_base_dir }}'
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755

- name: Ensure Elasticsearch service is started and enabled at boot.
  service:
    name: elasticsearch
    state: started
    enabled: yes
