---
# tasks file for ansible-role-elasticsearch

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/Install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Configure.
- include: configure.yml
