---
# tasks file for RedHat

- name: Ensure Elasticsearch repo file exists.
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644
  when: elasticsearch_repo

- name: Ensure Elasticsearch packages are installed (RedHat).
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ elasticsearch_packages }}'
